{
 "title": "APOD",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "APOD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP 200 Responses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(image_gallery_requests_total{code=\"200\"}) without(instance)"
    }
   ]
  },
  {
   "title": "In-Flight Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(image_gallery_in_flight_requests) without(instance)"
    }
   ]
  },
  {
   "title": "Memory In Use",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"apod-web\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Goroutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"apod-web\"}) without(instance)"
    }
   ]
  },
  { "title": "Image of the Day API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Get Image Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(method_timed_seconds_count{class=\"iotd.ImageController\",exception=\"none\",method=\"get\"}) without(instance, class, exception, method)"
    }
   ]
  },
  {
   "title": "Image Loads from NASA",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sum(iotd_api_image_load_total{status=\"success\"}) without(instance)"
    }
   ]
  },
  {
   "title": "Image Loads from Cache",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum(iotd_api_image_load_total{status=\"cached\"}) without(instance)"
    }
   ]
  },
  {
   "title": "JVM Memory Use",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes) without(area, id, instance)"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{job=\"apod-api\"}) without(instance)"
    }
   ]
  },
  { "title": "Access Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Logs by Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "access_log_total", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Current Client IPs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(access_client_ip_current) without(hostname, instance)"
    }
   ]
  },
  {
   "title": "Memory Use by Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_external_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Active Sockets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_active_handles{type=\"Socket\"}) without (instance)"
    }
   ]
  }
 ]
}