Vagrant.configure("2") do |config|
    config.vm.synced_folder "./", "/vagrant", type: "rsync", disabled: false
    config.vm.box_check_update = false
    config.vbguest.auto_update = false # disable OS related updates on boot
    config.vm.network "forwarded_port", guest: 22, host: 22, # SSH
    auto_correct: true # fix port collisions

    config.vm.define "CentOS7" do |centOS7|
        centOS7.vm.box = "centos/7"
        centOS7.vm.hostname = "CentOS7"
        centOS7.vm.network "public_network", ip: "192.168.1.10"
        centOS7.vm.provision "shell", inline: "echo CentOS 7 && cat /vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
    end 

    config.vm.define "Ubuntu" do |ubuntu|
        ubuntu.vm.box = "ubuntu/bionic64"
        ubuntu.vm.hostname = "Ubuntu"
        ubuntu.vm.network "public_network", ip: "192.168.2.10"
        ubuntu.vm.provision "shell", inline: "echo Ubuntu 7 && cat /vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
    end

end