- name: Add Prometheus helm repository
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: "{{ prometheus_repo }}"
  tags: prometheus   

- name: Deploy Prometheus latest version
  community.kubernetes.helm:
    name: prometheus 
    chart_ref: prometheus-community/prometheus
    release_namespace: prometheus
    values:
      global:
        scrape_interval: 10s
      serverFiles:
        prometheus.yml:
          scrape_configs:
            - job_name: "apod-web"
              static_configs:
                - targets: ["apod-web"]

            - job_name: "apod-log"
              static_configs:
                - targets: ["apod-log"]

            - job_name: "apod-api"
              metrics_path: /actuator/prometheus
              static_configs:
                - targets: ["apod-api"]
      server: # prometheus-server
        service:
          type: NodePort
          nodePort: 30487
  tags: prometheus