- name: Add Prometheus helm repository
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: "{{ prometheus_repo }}"
  tags: prometheus   

- name: Deploy Prometheus latest version
  community.kubernetes.helm:
    name: prometheus 
    chart_ref: prometheus-community/prometheus
    release_namespace: prometheus
    values:
      global:
        scrape_interval: 10s
      serverFiles:
        prometheus.yml:
          scrape_configs:
            - job_name: 'default'
              kubernetes_sd_configs:
              - role: pod 
              relabel_configs:
              - source_labels: 
                  - __meta_kubernetes_namespace
                action: keep
                regex: prometheus # Match to prometheus namespace
              - source_labels: 
                  - __meta_kubernetes_pod_annotationpresent_prometheus_io_scrape
                  - __meta_kubernetes_pod_annotation_prometheus_io_scrape
                regex: true;false 
                action: drop
              - source_labels: 
                  - __meta_kubernetes_pod_annotationpresent_prometheus_io_path
                  - __meta_kubernetes_pod_annotation_prometheus_io_path
                regex: true;(.*)
                target_label:  __metrics_path__
              - source_labels: 
                  - __meta_kubernetes_pod_annotationpresent_prometheus_io_target
                  - __meta_kubernetes_pod_annotation_prometheus_io_target
                regex: true;(.*)
                target_label:  __param_target
              - source_labels: 
                  - __meta_kubernetes_pod_annotationpresent_prometheus_io_port
                  - __address__
                  - __meta_kubernetes_pod_annotation_prometheus_io_port
                action: replace
                regex: true;([^:]+)(?::\d+)?;(\d+)
                replacement: $1:$2
                target_label: __address__
              - source_labels: 
                  - __meta_kubernetes_pod_labelpresent_app
                  - __meta_kubernetes_pod_label_app
                regex: true;(.*)
                target_label: job
              - source_labels: 
                  - __meta_kubernetes_pod_name
                target_label: instance
      server: # prometheus-server
        service:
          type: NodePort
          nodePort: 30487
  tags: prometheus