- name: Add Prometheus helm repository
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: "{{ prometheus_repo }}"
  tags: prometheus   

- name: Create Prometheus ConfigMap 
  community.kubernetes.k8s:
    state: present 
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: prometheus
        namespace: prometheus
      data:
        prometheus.yml: |-
          global:
            scrape_interval: 10s

          scrape_configs:
            - job_name: "apod-web"
              static_configs:
                - targets: ["apod-web"]

            - job_name: "apod-log"
              static_configs:
                - targets: ["apod-log"]

            - job_name: "apod-api"
              metrics_path: /actuator/prometheus
              static_configs:
                - targets: ["apod-api"]
    tags: prometheus

- name: Deploy Prometheus latest version
  community.kubernetes.helm:
    name: prometheus 
    chart_ref: prometheus-community/prometheus
    release_namespace: prometheus
    values:
      configMapOverrideName: prometheus
      server: # prometheus-server
        service:
          type: NodePort
  tags: prometheus